### ISSUE TITLE
Can you provide the code of Hourglass backbone about the CenterNet?Thanks a lot.

### ISSUE THREAD

**Issue by 201814476285951** [zzzxxxttt/pytorch_simple_classification_baselines#1]

**Comment by zzzxxxttt** [comment]
I'll release my version of CenterNet after validating the performance, but I'm curious why you ask me for the hourglass code? you can check the [official repository](https://github.com/xingyizhou/CenterNet).

**Comment by zzzxxxttt** [comment]
My implementation of CenterNet is now [released](https://github.com/zzzxxxttt/pytorch_simple_centernet_45)!
